/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Toolkit;
import javax.swing.*;
import utils.MySQLConnect;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import entity.UserAccount;

/**
 *
 * @author nguyentu
 */
public class FrLogin extends javax.swing.JFrame {
    public String userName;
    public String passWord;
    
    UserAccount user = new UserAccount('A001', 'CV001', 'user1', 'password1', 'Nguyễn Văn A', 'Hà Nội', 'user1@example.com');

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserName() {
        return userName;
    }
    /**
     * Creates new form login
     */
    public FrLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login to system");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jSeparator2.setAlignmentX(10.0F);

        btnOk.setBackground(new java.awt.Color(102, 153, 255));
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");
        btnOk.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                btnOkComponentHidden(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(102, 153, 255));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnCancelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtUserName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //setUserName(txtUserName.getText());
        userName = new String(txtUserName.getText());
        passWord = new String(txtPassword.getPassword());
        String chucVu = null;
        StringBuilder sb = new StringBuilder();
        boolean checkBothEmpty = false;
        boolean checkOneEmpty = false;
        if(userName.equals("") && passWord.equals("")){
            checkBothEmpty = true;
        }
        if(userName.equals("") && checkBothEmpty == false){
            checkOneEmpty = true;
         sb.append("Tài khoản không được bỏ trống"); 
         
        }
        if(passWord.equals("") && checkBothEmpty == false){
            checkOneEmpty = true;
            sb.append("Mật khẩu không được bỏ trống");
        }
        if (checkBothEmpty == true)
        {
            JOptionPane.showMessageDialog(this,"Tài khoản và mật khẩu không được bỏ trống", "Authentication",JOptionPane.ERROR_MESSAGE);
        }
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this,sb.toString(), "Authentication",JOptionPane.ERROR_MESSAGE);
        }
        boolean isValid = checkCredentials(userName, passWord);
        if (isValid){
            sb.append(userName);
            JOptionPane.showMessageDialog(this, "Xin chào " + sb.toString(), "Success", JOptionPane.INFORMATION_MESSAGE);
             FrMain frmain = new FrMain();
             frmain.setFrLogin(this);
             frmain.runMain();
             setVisible(false);
        }
        else{
               if(checkBothEmpty == false && checkOneEmpty == false){
                 JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu sai", "Authentication", JOptionPane.ERROR_MESSAGE);
               }               
            }            
    }//GEN-LAST:event_btnOkActionPerformed
    public String getChucVu(String userName){
        String chucVu = null;
    try{
        Connection connection = MySQLConnect.getConnection();
        String query = "SELECT ChucVu.tenChucVu FROM UserAccount "
                + "JOIN ChucVu ON UserAccount.idChucVu = ChucVu.idChucVu WHERE userName = ?";
        try(PreparedStatement statement = connection.prepareStatement(query) ){
            statement.setString(1,userName);
            try{
                ResultSet rs = statement.executeQuery();
                if(rs.next()){
                    chucVu = rs.getString("tenChucVu");
                }
            }catch(SQLException e){
                e.printStackTrace();
            }
    }

    }catch(SQLException e){
         e.printStackTrace();
    }
     return chucVu;   
}
    
    private  boolean checkCredentials(String userName, String passWord){
        String chucVu = null;
        boolean isValid = false;
        try{
            Connection connection = MySQLConnect.getConnection();
            String query = "SELECT COUNT(*) FROM UserAccount WHERE userName = ? AND passWord = ?";
            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, userName);
                statement.setString(2, passWord);
                try(ResultSet rs = statement.executeQuery()){
                    if(rs.next()){
                        int count = rs.getInt(1);
                        isValid = (count > 0);
                    }
                }
            }
        }catch(SQLException e){
            e.printStackTrace();
            
        }
        return isValid;
    }
            
    private void btnCancelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnCancelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelAncestorAdded

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnOkComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnOkComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
            
             FrLogin frlogin = new FrLogin();
            int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width;
            int screenHeight = Toolkit.getDefaultToolkit().getScreenSize().height;
            int x = (screenWidth - frlogin.getWidth()) / 2;
            int y = (screenHeight - frlogin.getHeight()) / 2;
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frlogin.setLocation(x, y);
                frlogin.setVisible(true);
                frlogin.setResizable(false); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
