/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
// import sql librabry
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import utils.MySQLConnect;
import java.awt.Toolkit;
// import file
import entity.*;
import view.*;
import controller.MainController;
import controller.DoUongController;
import controller.LoginController;

// import other library
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyentu
 */
public class FrMain extends javax.swing.JFrame {
    // properties
    public FrLogin frLogin;
    public FrMain frMain;
    public FrDoUong frDoUong;
    public FrNhanVien frNhanVien;
    public MainController mainController;   
    public FrHoaDon frHoaDon;
    /**
     *
     * @param mainContrloller
     */

    /**
     * Creates new form FrMain
     */
    // constructor 
    public FrMain(){
        initComponents();
        setTitle("Thông tin quán");
        pnXinChao.setSize(50, 50);
        setBackground(new java.awt.Color(255, 255, 204));
    }
    // setter for controller of 
    public void setMainController(MainController mainController){
        this.mainController = mainController;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        pnXinChao = new javax.swing.JPanel();
        lbXinChao = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDoUong = new javax.swing.JButton();
        btnKho = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();

        jButton4.setText("jButton1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 300));
        setSize(new java.awt.Dimension(100, 100));

        pnXinChao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnXinChao.setMaximumSize(new java.awt.Dimension(100, 100));
        pnXinChao.setPreferredSize(new java.awt.Dimension(197, 67));
        pnXinChao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnXinChaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbXinChao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbXinChao.setText("Xin chào: ");
        lbXinChao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbXinChaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbChucVu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbChucVu.setForeground(new java.awt.Color(255, 0, 0));
        lbChucVu.setText("Chức vụ:");
        lbChucVu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbChucVuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout pnXinChaoLayout = new javax.swing.GroupLayout(pnXinChao);
        pnXinChao.setLayout(pnXinChaoLayout);
        pnXinChaoLayout.setHorizontalGroup(
            pnXinChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXinChaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXinChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbXinChao)
                    .addComponent(lbChucVu))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        pnXinChaoLayout.setVerticalGroup(
            pnXinChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXinChaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbXinChao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbChucVu)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        btnDoUong.setBackground(new java.awt.Color(102, 153, 255));
        btnDoUong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDoUong.setForeground(new java.awt.Color(255, 255, 255));
        btnDoUong.setText("ĐỒ UỐNG");
        btnDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoUongActionPerformed(evt);
            }
        });

        btnKho.setBackground(new java.awt.Color(102, 153, 255));
        btnKho.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKho.setForeground(new java.awt.Color(255, 255, 255));
        btnKho.setText("KHO");

        btnNhanVien.setBackground(new java.awt.Color(102, 153, 255));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(102, 153, 255));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setText("HOÁ ĐƠN");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoUong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        frNhanVien = new FrNhanVien();
        frNhanVien.setMainController(mainController);
        frNhanVien.runMain();
        setVisible(false);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void lbXinChaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbXinChaoAncestorAdded
        String fullName = mainController.loginController.userAccount.fullName;
        lbXinChao.setText("Xin chào " + fullName);
    }//GEN-LAST:event_lbXinChaoAncestorAdded

    private void lbChucVuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbChucVuAncestorAdded
        String chucVu = mainController.loginController.chucVu.getTenChucVu();
        lbChucVu.setText("Chức vụ: " + chucVu);
    }//GEN-LAST:event_lbChucVuAncestorAdded

    private void pnXinChaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnXinChaoAncestorAdded

    }//GEN-LAST:event_pnXinChaoAncestorAdded

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        frHoaDon = new FrHoaDon();
        frHoaDon.setMainController(mainController);
        frHoaDon.runMain();
        setVisible(false);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoUongActionPerformed
        frDoUong = new FrDoUong();
        frDoUong.setMainController(mainController);
        frDoUong.runMain();
        setVisible(false);
    }//GEN-LAST:event_btnDoUongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
        public void runMain(){
            FrMain frMain = new FrMain();
            int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width;
            int screenHeight = Toolkit.getDefaultToolkit().getScreenSize().height;
            int x = (screenWidth - getWidth()) / 2;
            int y = (screenHeight - getHeight()) / 2;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                setLocation(x, y);
                setResizable(false); 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoUong;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKho;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbXinChao;
    private javax.swing.JPanel pnXinChao;
    // End of variables declaration//GEN-END:variables


}

