/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
// import file
import controller.MainController;
import controller.NhanVienController;
import entity.UserAccount;
// other librabry
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author nguyentu
 */
public class FrSuaNhanVien extends javax.swing.JFrame {
    
    // properties
    public FrNhanVien frNhanVien;
    public FrSuaNhanVien frSuaNhanVien;
    public MainController mainController;
    public NhanVienController nhanVienController;
    public UserAccount userAccount;
    
    
    
    /**
     * Creates new form FrSuaNhanVien
     */
    // main constructor
    public FrSuaNhanVien() {
        setTitle("Sửa thông tin nhân viên");
        initComponents();
    }
    
    //getter and setter

    public MainController getMainController() {
        return mainController;
    }

    public void setMainController(MainController mainController) {
        this.mainController = mainController;
    }

    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtGiaBan4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNhapTaiKhoan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtHoVaTen = new javax.swing.JTextField();
        btnXoaThongTinCu2 = new javax.swing.JButton();
        btnLuu2 = new javax.swing.JButton();
        btnCancel2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNoiO = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbChucVu = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnTroVe = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        lbLoi = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Nơi ở");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SỬA THÔNG TIN NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nhập tài khoản");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Tài khoản");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Mật khẩu");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Họ và tên");

        btnXoaThongTinCu2.setBackground(new java.awt.Color(102, 153, 255));
        btnXoaThongTinCu2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnXoaThongTinCu2.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaThongTinCu2.setText("Xoá thông tin cũ");
        btnXoaThongTinCu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThongTinCu2ActionPerformed(evt);
            }
        });

        btnLuu2.setBackground(new java.awt.Color(102, 153, 255));
        btnLuu2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnLuu2.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu2.setText("Lưu");
        btnLuu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu2ActionPerformed(evt);
            }
        });

        btnCancel2.setBackground(new java.awt.Color(102, 153, 255));
        btnCancel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCancel2.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel2.setText("Cancel");
        btnCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Nơi ở");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Chức vụ");

        cbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"----","Nhân viên", "Quản lý", "Giám đốc"}));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Email");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnXoaThongTinCu2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLuu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoiO)
                            .addComponent(txtHoVaTen)
                            .addComponent(txtMatKhau)
                            .addComponent(txtTaiKhoan)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(61, 61, 61)
                        .addComponent(txtEmail)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNoiO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaThongTinCu2)
                    .addComponent(btnLuu2)
                    .addComponent(btnCancel2))
                .addContainerGap())
        );

        btnTroVe.setBackground(new java.awt.Color(102, 153, 255));
        btnTroVe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTroVe.setForeground(new java.awt.Color(255, 255, 255));
        btnTroVe.setText("< Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        btnOk.setBackground(new java.awt.Color(102, 153, 255));
        btnOk.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lbLoi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbLoi.setForeground(new java.awt.Color(255, 0, 0));
        lbLoi.setText("*Nhập thông tin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTroVe)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNhapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnOk)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(btnTroVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLoi))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaThongTinCu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThongTinCu2ActionPerformed
        txtHoVaTen.setText("");
        txtMatKhau.setText("");
        txtNoiO.setText("");
        txtEmail.setText("");
        cbChucVu.setSelectedItem("----");
    }//GEN-LAST:event_btnXoaThongTinCu2ActionPerformed

    private void btnLuu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu2ActionPerformed
        nhanVienController = new NhanVienController();
        if(!checkEmpty()){
            String inputUserName = txtNhapTaiKhoan.getText();
            String fullName = txtHoVaTen.getText();
            String password = txtMatKhau.getText();
            String address = txtNoiO.getText();
            String userName = txtTaiKhoan.getText();
            String email = txtEmail.getText();
            String tempChucVu = (String) cbChucVu.getSelectedItem();
            String idChucVu = nhanVienController.getIDChucVu(tempChucVu);
            userAccount = new UserAccount(idChucVu, userName, password, fullName, address, email);
            nhanVienController.update(userAccount, inputUserName);
            txtHoVaTen.setText("");
            txtMatKhau.setText("");
            txtNoiO.setText("");
            txtTaiKhoan.setText("");
            txtEmail.setText("");
            txtNhapTaiKhoan.setText("");
            cbChucVu.setSelectedItem("----");
            JOptionPane.showMessageDialog(this, "Sửa thành công", "Success", JOptionPane.INFORMATION_MESSAGE);           
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Không được để trống", "Error", JOptionPane.ERROR_MESSAGE);           
        }
        
        // UPDATE UserAccount SET idChucVu = ?, userName = ?,passWord = ?, fullName = ?, address = ?, email = ? WHERE userName = ?
    }//GEN-LAST:event_btnLuu2ActionPerformed

    public Boolean checkEmpty(){
        Boolean check = false;
        String inputUserName = txtNhapTaiKhoan.getText();
        String fullName = txtHoVaTen.getText();
        String password = txtMatKhau.getText();
        String address = txtNoiO.getText();
        String userName = txtTaiKhoan.getText();
        String email = txtEmail.getText();
        String tempChucVu = (String) cbChucVu.getSelectedItem();
        if(inputUserName.isEmpty() || fullName.isEmpty() || password.isEmpty() || address.isEmpty() || userName.isEmpty() ||
        email.isEmpty() || tempChucVu == "----"){
            check = true;
        }
        return check;
    }

    private void btnCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel2ActionPerformed
        FrNhanVien frNhanVien = new FrNhanVien();
         frNhanVien.setMainController(mainController);
         frNhanVien.runMain();
         setVisible(false);
         dispose();
    }//GEN-LAST:event_btnCancel2ActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
         FrNhanVien frNhanVien = new FrNhanVien();
         frNhanVien.setMainController(mainController);
         frNhanVien.runMain();
         setVisible(false);
         dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        txtHoVaTen.setText("");
        txtMatKhau.setText("");
        txtNoiO.setText("");
        txtTaiKhoan.setText("");
        txtEmail.setText("");
        lbLoi.setText("*Nhập tài khoản");
        cbChucVu.setSelectedItem("----");
        String userName = txtNhapTaiKhoan.getText();
        nhanVienController = new NhanVienController();
        if(nhanVienController.find(userName)){
            lbLoi.setText("*Đã tìm thấy tài khoản");
            frSuaNhanVien = new FrSuaNhanVien();
            frSuaNhanVien.setUserAccount(nhanVienController.getUser());
            String tempUserName = frSuaNhanVien.userAccount.userName;
            String passWord = frSuaNhanVien.userAccount.passWord;
            String fullName = frSuaNhanVien.userAccount.fullName;
            String address = frSuaNhanVien.userAccount.address;
            String email = frSuaNhanVien.userAccount.email;
            String idChucVu = frSuaNhanVien.userAccount.idChucVu;
            String tenChucVu = nhanVienController.getTenChucVu(idChucVu);
            lbLoi.setText("");
            txtTaiKhoan.setText(tempUserName);
            txtMatKhau.setText(passWord);
            txtHoVaTen.setText(fullName);
            txtNoiO.setText(address);
            txtEmail.setText(email);
            cbChucVu.setSelectedItem(tenChucVu);
        }
        else{
            lbLoi.setText("*Không tìm thấy");
        }
        
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSuaNhanVien().setVisible(true);
            }
        });
    }
    public void runMain(){    
        int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width;
        int screenHeight = Toolkit.getDefaultToolkit().getScreenSize().height;
        int x = (screenWidth - getWidth()) / 2;
        int y = (screenHeight -getHeight()) / 2;
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        setVisible(true);
        setLocation(x, y);
        setResizable(false);
        }
});
}
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel2;
    private javax.swing.JButton btnLuu2;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JButton btnXoaThongTinCu2;
    private javax.swing.JComboBox<String> cbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbLoi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGiaBan4;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNhapTaiKhoan;
    private javax.swing.JTextField txtNoiO;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
