/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
// import file
import controller.HoaDonController;
import controller.MainController;
import entity.HoaDon;
import entity.CTHD;
import utils.MySQLConnect;
// import sql librabry
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
// import other library
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author nguyentu
 */
public class FrThemDoUong extends javax.swing.JFrame {

    /**
     * Creates new form FrThemMonAn
     */
    // properties
    public FrHoaDon frHoaDon;
    public FrXoaDoUongCTHD frXoaDoUongCTHD;
    public MainController mainController;
    public HoaDonController hoaDonController;
    public HoaDon hoaDon;
    public CTHD cthd;
    
    
    //setter
    public void setMainController(MainController mainController) {
        this.mainController = mainController;
    }
    public void setHoaDonController(HoaDonController hoaDonController){
        this.hoaDonController = hoaDonController;
    }
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }
    
    

    // main constructor
    public FrThemDoUong() {
        setTitle("Chi tiết hoá đơn");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btnTrangChu2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCTHD = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDoUong = new javax.swing.JTextField();
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(0, 0, 100, 1);
        spSoLuong = new javax.swing.JSpinner(spinnerModel);
        btnThem2 = new javax.swing.JButton();
        btnXong = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("CHI TIẾT HOÁ ĐƠN");

        btnTrangChu2.setBackground(new java.awt.Color(102, 153, 255));
        btnTrangChu2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTrangChu2.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu2.setText("< Trang chủ");
        btnTrangChu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu2ActionPerformed(evt);
            }
        });

        tbCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Đồ uống", "Số lượng", "Giá"
            }
        ));
        tbCTHD.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbCTHDAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbCTHD);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm đồ uống", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Tên đồ uống");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Số lượng");

        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) spSoLuong.getEditor();
        editor.getTextField().setEditable(false);
        spSoLuong.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spSoLuongAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnThem2.setBackground(new java.awt.Color(102, 153, 255));
        btnThem2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThem2.setForeground(new java.awt.Color(255, 255, 255));
        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnXong.setBackground(new java.awt.Color(102, 153, 255));
        btnXong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXong.setForeground(new java.awt.Color(255, 255, 255));
        btnXong.setText("Xong");
        btnXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXongActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 153, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTenDoUong, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addComponent(btnXong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnXong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTrangChu2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangChu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu2ActionPerformed
        if(tbCTHD.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đồ uống", "Error", JOptionPane.ERROR_MESSAGE); 
        }else{
            FrHoaDon frHoaDon = new FrHoaDon();
            hoaDonController = new HoaDonController();
            frHoaDon.setMainController(mainController);
            frHoaDon.setHoaDon(hoaDon);
            hoaDonController.updateThanhTien();
            frHoaDon.runMain();
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btnTrangChu2ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        if(checkEmpty()){
            JOptionPane.showMessageDialog(this, "Không được để trống", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        else{
            String tenDoUong = txtTenDoUong.getText();
            int soLuong = (int) spSoLuong.getValue();
            hoaDonController = new HoaDonController();
            if(hoaDonController.checkExist(tenDoUong)){
                String idDoUong = hoaDonController.changeIdDoUong(tenDoUong);
                hoaDon.cthd = new CTHD(idDoUong, soLuong);
                Integer idHoaDon = hoaDon.idHoaDon;
                hoaDonController.createCTHD(idHoaDon,hoaDon.cthd);
                JOptionPane.showMessageDialog(this, "Nhập thành công", "Success", JOptionPane.INFORMATION_MESSAGE);           
            }
            else{
                JOptionPane.showMessageDialog(this, "Tên đồ uống hiện không tồn tại", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            
        }
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXongActionPerformed
        if(tbCTHD.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đồ uống", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        else{
            frHoaDon = new FrHoaDon();
            hoaDonController = new HoaDonController();
            frHoaDon.setMainController(mainController);
            frHoaDon.setHoaDon(hoaDon);
            hoaDonController.updateThanhTien();
            frHoaDon.runMain();
            setVisible(false);
            dispose();
        }
        
    }//GEN-LAST:event_btnXongActionPerformed
    // Hiển thị các thông tin đồ uống hiện tại của CTHD lên JTable
    private void tbCTHDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbCTHDAncestorAdded
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Đồ uống");
        model.addColumn("Số lượng");
        model.addColumn("Giá");
        tbCTHD.setModel(model);
        TimerTask updateTask = new TimerTask() {
            @Override
            public void run(){
                try{    
                    Connection connection = MySQLConnect.getConnection();
                    String query = "SELECT DoUong.tenDoUong, CTHD.soLuong, (CTHD.soLuong * DoUong.price) AS totalPrice\n" +
"				   FROM CTHD\n" +
"				   JOIN DoUong ON DoUong.idDoUong = CTHD.idDoUong\n" +
"				   WHERE CTHD.idHoaDon = ?";
                    PreparedStatement statement = connection.prepareStatement(query);
                    statement.setInt(1,hoaDon.idHoaDon);
                    ResultSet rs = statement.executeQuery();
                    model.setRowCount(0);
                    while(rs.next()){
                        String tenDoUong = rs.getString("tenDoUong");
                        String soLuong = rs.getString("soLuong");
                        Double gia = rs.getDouble("totalPrice");
                        model.addRow(new Object[]{tenDoUong, soLuong, gia});
                        
                    }
                } catch(SQLException e){
                    e.printStackTrace();
                }
            }
        };
    Timer timer = new Timer();
    timer.scheduleAtFixedRate(updateTask, 0, 1000);
    }//GEN-LAST:event_tbCTHDAncestorAdded

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        frXoaDoUongCTHD = new FrXoaDoUongCTHD();
        frXoaDoUongCTHD.setMainController(mainController);
        frXoaDoUongCTHD.setHoaDon(hoaDon);
        frXoaDoUongCTHD.runMain();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void spSoLuongAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spSoLuongAncestorAdded
  
    }//GEN-LAST:event_spSoLuongAncestorAdded
    public boolean checkEmpty(){
        Boolean check = false;
        String tenDoUong = txtTenDoUong.getText();
        int soLuong = (int) spSoLuong.getValue();
        if(tenDoUong.isEmpty()|| soLuong == 0){
            check = true;
        }
        return check;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrThemDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrThemDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrThemDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrThemDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrThemDoUong().setVisible(true);
            }
        });
    }
    public void runMain(){
        // FrMain frMain = new FrMain();
        int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width;
        int screenHeight = Toolkit.getDefaultToolkit().getScreenSize().height;
        int x = (screenWidth - getWidth()) / 2;
        int y = (screenHeight - getHeight()) / 2;
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            setVisible(true);
            setLocation(x, y);
            setResizable(false); 
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnTrangChu2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spSoLuong;
    private javax.swing.JTable tbCTHD;
    private javax.swing.JTextField txtTenDoUong;
    // End of variables declaration//GEN-END:variables
}
